### PR TITLE
Update user entity

### PR DESCRIPTION
**Pull request by VladyslavIvanov09**
This pull request is related to issue #8.

Related PR: [https://github.com/bakaydmytro/team_seeker_be/pull/13](https://github.com/bakaydmytro/team_seeker_be/pull/13)

### CODE REVIEW

**Comment by bakaydmytro** [comment]
The root of the Node.js project should include files like package.json, package-lock.json, etc. All code files should be inside the src folder.

**Comment by bakaydmytro** [comment]
We are not merging code into the main branch, as it’s a production branch. For now, please create the pull request into the dev branch.

**Comment by NataliaVoloshynska** [comment]
Everything must be written in English, including comments and explanations.

**Comment by bakaydmytro** [comment]
@VladyslavIvanov09 please also note that the task involves updating the user entity. This means you need to create an endpoint for updating user data by user ID
PUT /api/user/{user_id}

**Review by bakaydmytro — APPROVED** [review]

**Pull request merged**
